allowed_topics_expanded = [
    # full phrases (lowercased)
    "airtel partner portal",
    "partner onboarding",
    "business validations",
    "kyc submission",
    "onboarding type",
    "partner metadata",
    "partner id",
    "partner name",
    "primary contact details",
    "partner status",
    "environment access",
    "dev environment",
    "uat environment",
    "preprod environment",
    "prod environment",
    "base urls",
    "oauth2 authentication",
    "saml sso authentication",
    "environment description",
    "workflow automation",
    "approval workflows",
    "escalation workflows",
    "api dashboard",
    "api usage",
    "api latency",
    "api error count",
    "quota balance",
    "role management",
    "assigning roles",
    "reset credentials",
    "audit activity",
    "audit logs",
    "api catalog",
    "get partner profile api",
    "submit onboarding docs api",
    "generate access token api",
    "api access token generation",
    "non-functional requirements",
    "concurrent partner users",
    "uptime requirements",
    "data encryption",
    "page load performance",
    "sla",
    "workflow definition",

    # unique split words (lowercased)
    "airtel", "partner", "portal", "onboarding", "business", "validations",
    "kyc", "submission", "type", "metadata", "id", "name",
    "primary", "contact", "details", "status", "environment", "access",
    "dev", "uat", "preprod", "prod", "base", "urls", "oauth2",
    "authentication", "saml", "sso", "description", "workflow",
    "automation", "approval", "workflows", "escalation", "api",
    "dashboard", "usage", "latency", "error", "count", "quota",
    "balance", "role", "management", "assigning", "roles", "reset",
    "credentials", "audit", "activity", "logs", "catalog", "get",
    "profile", "docs", "generate", "access", "token", "generation",
    "non-functional", "requirements", "concurrent", "users",
    "uptime", "data", "encryption", "page", "load", "performance",
    "sla", "definition"
]
